apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  # Hard coded in the operator code, for now.
  name: "piraeus-priority-class"
value: 1000000
globalDefault: false
description: "Priority class for piraeus components"
