apiVersion: piraeus.linbit.com/v1alpha1
kind: PiraeusNodeSet
metadata:
  name: {{ template "piraeus-operator.fullname" . }}
spec:
  disableDRBDKernelModuleInjection: {{ .Values.operator.nodeSet.spec.disableDRBDKernelModuleInjection }}
  storagePools:
    lvmThinPools:
    - name: "lvm-thin"
      volumeGroup: "lvm-0"
      thinVolume: "lvm-0-thin"
