kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ template "piraeus-operator.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ template "piraeus-operator.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
